version: "3"
services:
  db:
    image: postgres:11.1-alpine
  web:
    build: .
    command: 'puma -C config/puma.rb'
    volumes:
      - .:/usr/src/app
      - bundle_path:/bundle
    environment:
      - BUNDLE_PATH=/bundle/vendor
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  bundle_path: 
